#!/bin/sh
### BEGIN INIT INFO
# Provides:          ArduPlane
# Required-Start:    
# Required-Stop:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ArduPlane Autopilot Daemon
# Description:       starts ArduPlane Autopilot
### END INIT INFO

STARTCMD="ArduPlane -C /dev/ttyAMA0"
#STARTCMD="ArduCopter -C /dev/ttyAMA0"

PIDFILE=/var/run/arduplane.pid

start(){
        if [ -f /var/run/$PIDFILE ] && kill -0 $(cat /var/run/$PIDFILE); then
                echo 'Service already running' >&2
                return 1
        fi
        echo 'Starting service…' >&2
        local CMD="$STARTCMD &> /home/pi/arduplane.log & echo \$!"
        su -c "$CMD" root > "$PIDFILE"
        echo 'Service started' >&2
}

stop(){
	if [ ! -f /var/run/$PIDFILE ] || ! kill -0 $(cat /var/run/$PIDFILE); then
                echo 'Service not running' >&2
                return 1
        fi
        echo 'Stopping service…' >&2
        kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
        echo 'Service stopped' >&2
}

# Actions
case "$1" in
    start)
	start
        ;;
    stop)
	stop
        ;;
    restart)
	stop
	start
        ;;
esac
 
exit 0
